# Generated by Django 5.0.2 on 2024-04-06 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bless',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bless', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
