# Generated by Django 5.0.2 on 2024-04-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bless', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='like',
            field=models.IntegerField(default=0, verbose_name='like'),
        ),
    ]
