# Generated by Django 5.0.2 on 2024-04-10 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bless', '0005_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo', verbose_name='image')),
                ('discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='bless.discuss')),
            ],
        ),
    ]
