# Generated by Django 5.0.2 on 2024-04-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bless', '0006_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='discuss', verbose_name='image'),
        ),
    ]
