# Generated by Django 5.0.2 on 2024-04-10 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bless', '0007_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='discuss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='bless.discuss'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
