# Generated by Django 5.0.2 on 2024-04-06 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_map_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermap', to='map.map')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermap', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
