# Generated by Django 5.0.2 on 2024-04-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_usermap'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='nation',
            field=models.CharField(default=1, max_length=32, verbose_name='nation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='map',
            name='value',
            field=models.IntegerField(default=10, verbose_name='value'),
        ),
    ]
