# Generated by Django 5.0.2 on 2024-03-14 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='专业名称')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('degree', models.CharField(choices=[('1', '专科生'), ('2', '本科生'), ('3', '联培本科'), ('4', '硕士研究生'), ('5', '联培硕士'), ('6', '博士研究生'), ('7', '联培博士'), ('8', '博士后'), ('9', '继续教育和培训')], max_length=2, verbose_name='学位')),
                ('status', models.CharField(choices=[('1', '在读'), ('2', '毕业')], max_length=2, verbose_name='学籍状态')),
                ('start_time', models.DateField(verbose_name='入学时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='毕业时间')),
                ('Diploma', models.ImageField(blank=True, null=True, upload_to='student/', verbose_name='学历证书')),
                ('Degree_certificate', models.ImageField(blank=True, null=True, upload_to='student/', verbose_name='学位证书')),
                ('professional', models.CharField(max_length=100, verbose_name='专业名称')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='user.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('status', models.CharField(choices=[('1', '在职'), ('2', '已离职')], max_length=2, verbose_name='在职状态')),
                ('start_time', models.DateField(verbose_name='入职时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='离职时间')),
                ('department', models.CharField(max_length=100, verbose_name='部门名称')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('work_certificate', models.ImageField(upload_to='teacher/', verbose_name='工作证')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='user.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='培养单位名称')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_unit', to='authentication.student')),
            ],
        ),
    ]
