# Generated by Django 5.0.2 on 2024-03-14 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('openid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=400, null=True, verbose_name='微信session_key')),
                ('roles', models.IntegerField(choices=[(1, '普通用户'), (2, '管理员')], default=1)),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='自我介绍')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话号码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('authentication_status', models.IntegerField(choices=[(1, '未认证'), (2, '认证中'), (3, '已认证')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='头像')),
                ('avatar_name', models.CharField(max_length=100, verbose_name='头像名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='user.userinfo')),
            ],
        ),
    ]
