# Generated by Django 5.0.2 on 2024-04-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='qq',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='QQ号'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='wechat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='微信号'),
        ),
    ]
